name = "project-sparkle"
compatibility_date = "2024-11-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "project_sparkle_db"
database_id = "c81bc360-7bb6-48d0-a7b7-a7dbc69d843c"
migrations_dir = "workers/d1/migrations"

[dev]
ip = "127.0.0.1"
port = 8787