name = "project-sparkle-db"
main = "workers/d1/worker.ts"
compatibility_date = "2024-11-01"
migrations_dir = "workers/d1/migrations"

[vars]
# Optional: if you want to consume a different API base in local dev
# API_BASE_URL = "http://127.0.0.1:8787"

[[d1_databases]]
binding = "DB"
database_name = "DB"
database_id = "icn_db"

[dev]
ip = "127.0.0.1"
port = 8787
