name = "project-sparkle"
compatibility_date = "2024-11-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "project_sparkle_db"
database_id = "ip_infection_db"
migrations_dir = "workers/d1/migrations"

[dev]
ip = "127.0.0.1"
port = 8787